# Generated by Django 4.2.11 on 2025-09-06 04:34

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import seatBokking.models


class Migration(migrations.Migration):

    dependencies = [
        ('seatBokking', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['date', 'departure_time']},
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='seatbooking',
            name='status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('pending', 'Pending')], default='confirmed', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_seats',
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AddField(
            model_name='trip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='seatbooking',
            name='seat_number',
            field=models.CharField(max_length=5, validators=[seatBokking.models.validate_seat_number]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(validators=[seatBokking.models.validate_future_date]),
        ),
        migrations.AlterField(
            model_name='trip',
            name='name',
            field=models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Trip name can only contain letters, numbers, spaces, hyphens, and underscores', regex='^[a-zA-Z0-9\\s\\-_]+$')]),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['user'], name='seatBokking_user_id_90dda3_idx'),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['status'], name='seatBokking_status_ae56c4_idx'),
        ),
        migrations.AddIndex(
            model_name='seatbooking',
            index=models.Index(fields=['booked_at'], name='seatBokking_booked__db39a4_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['date'], name='seatBokking_date_554814_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['is_active'], name='seatBokking_is_acti_491f50_idx'),
        ),
    ]
