# Generated by Django 4.2.11 on 2025-09-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seatBokking', '0002_alter_trip_options_seatbooking_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='day',
            field=models.CharField(blank=True, help_text='Day of the trip (e.g. Monday)', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.CharField(blank=True, help_text='Route of the bus trip', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='trip_time',
            field=models.CharField(blank=True, help_text='Time of the bus trip (e.g. 8:00 AM)', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
