# Generated by Django 4.2.11 on 2025-09-06 04:34

import django.core.validators
from django.db import migrations, models
import tracker.models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buslocation',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='buslocation',
            name='bus_id',
            field=models.CharField(blank=True, help_text='Optional bus identifier', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='direction',
            field=models.FloatField(blank=True, help_text='Direction in degrees (0-360, optional)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AddField(
            model_name='buslocation',
            name='speed',
            field=models.FloatField(blank=True, help_text='Speed in km/h (optional)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='lat',
            field=models.FloatField(help_text='Latitude coordinate (-90 to 90 degrees)', validators=[tracker.models.validate_latitude]),
        ),
        migrations.AlterField(
            model_name='buslocation',
            name='lng',
            field=models.FloatField(help_text='Longitude coordinate (-180 to 180 degrees)', validators=[tracker.models.validate_longitude]),
        ),
        migrations.AddIndex(
            model_name='buslocation',
            index=models.Index(fields=['timestamp'], name='tracker_bus_timesta_1e3195_idx'),
        ),
        migrations.AddIndex(
            model_name='buslocation',
            index=models.Index(fields=['bus_id'], name='tracker_bus_bus_id_b7a20c_idx'),
        ),
    ]
